version: '3.7'

services:
  testtemplate3.migrations:
    # image: ${DOCKER_REGISTRY-}testtemplate3sql
    env_file: .env
    build:
      context: .
      dockerfile: src/TestTemplate3.Migrations/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"